$ANSIBLE_VAULT;1.1;AES256
63316362366432326462326461386138363030323838363039396363646234363631626633353330
3838666562653532666364373530363438373738663333660a666363366336336531643837316463
39323237333736376337636334663262363562663235353061306635623938643035346662303065
3430666662363937320a666336623531313231626166666461303964396266646130303239326532
32306662373434663565636635633766343832376136363236386632333133613465333132636561
61636239663830613239336335343566386161656463663038306237616464663730613561356237
63323863643664393239653437633333316363363532633165616132303163656337303363633761
34623035363336633061656633376165333263356130323830663236626537663764643837663363
64333735393135623966363434323062316535313966356135653238626162643833666466633632
31613264313038363134383032663036623439656432306662346536656262643261386263336165
66356536656266363134646362353234616561383062386534646662663463613830363766663934
32613562353366386535613634373061393937346533313238366265373434393763653964383537
61343932353936636535323130346536643431613863346662643933363261363436343664323066
37393132343235383664666430636530373833363066343930323734633130316635626238326361
66366361653664373536376630653337353037623033353135653030356134313265613465396665
34643330623764356331
