$ANSIBLE_VAULT;1.1;AES256
62333632643135643738393039643464636536386264663336376566356333316562636132646232
3866333531636333626431626164666231646363643737300a306266363265656235343731303933
31396337366262373063393831306338336461356230316639376439383063363165366465373263
3635366334626462360a306234353931336464303531626362626164303964643762323662326331
65316166303038613730303961363561653663313532323230326164666433666266323430326266
33643137323738636230336633333263336635353737363539363831396334346533633662623435
64613539303865316636663761393438353639353464663231326563366432643038333232633765
31326231386536613938613637626263396561646639373338356366393162663538316232356161
39396333353432303065623333656232346531383161393330613031383633636633346234303039
6434343738393033333066336364336664373830623365313466
