---
all:
  children:
    gpu-fabric-cluster1:
      hosts:
        10.161.37.180:
        10.161.38.42:
        10.161.38.36:
        10.161.37.177:
        10.161.37.181:
        10.161.38.44:
        10.161.37.182:
        10.161.37.175:
        10.161.38.43:
        10.161.38.35:
        10.161.38.41:
        10.161.37.176:
        10.161.38.40:
        10.161.38.39:
        10.161.37.178:
        10.161.38.37:
        10.161.37.179:
        10.161.38.38:
        
