---
all:
  children:
    gpu-fabric-cluster1:
      hosts:
        10.161.33.38:
        10.161.33.39:
        10.161.34.248:
        10.161.34.249:
        10.161.38.17:
        10.161.38.29:
        10.161.38.30:
        10.161.38.35:
        10.161.38.36:
        10.161.38.37:
        10.161.38.38:
        10.161.38.39:
        10.161.38.40:
        10.161.38.41:
        10.161.38.42:
        10.161.38.43:
        10.161.38.44:
        10.161.38.51:
        10.161.38.52:
        10.161.38.53:
        10.161.38.142:
        10.161.38.143:
        10.161.37.113:
        10.161.37.164:
        10.161.37.175:
        10.161.37.176:
        10.161.37.177:
        10.161.37.178:
        10.161.37.179:
        10.161.37.180:
        10.161.37.181:
        10.161.37.182:
        10.10.1.0:
        10.10.1.2:
        10.10.1.4:
        10.10.1.6:
        10.10.1.8:
        10.10.1.10:
        10.10.1.12:
        10.10.1.16:
        10.10.1.18:
        10.10.1.20:
        10.161.32.15:
        10.161.32.16:
        10.161.38.17:
        10.161.32.52:
        10.161.32.53:
        10.161.32.64:
        10.161.32.65:
        10.161.32.96:
        10.161.32.97:






        
